services:
  db:
    image: postgres:16
    container_name: movies_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres/database_dump.sql:/docker-entrypoint-initdb.d/database_dump.sql
      - movies-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [
        "CMD-SHELL",
        "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"
      ]
      interval: 5s
      timeout: 5s
      retries: 5

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: movies_es
    restart: always
    env_file:
      - .env
    ports:
      - "9200:9200"
    healthcheck:
      test: curl -s http://es:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - movies-es-data:/usr/share/elasticsearch/data

  etl:
    build:
      context: ./etl
      dockerfile: Dockerfile
    container_name: movies_etl
    restart: always
    env_file:
      - .env
    environment:
      ES_HOST: es
      ES_PORT: 9200
      ES_INDEX: ${ES_INDEX}
      POLL_INTERVAL_SECONDS: ${POLL_INTERVAL_SECONDS}
      STORAGE_FILE_NAME: ${STORAGE_FILE_NAME}
      LOG_LEVEL: ${LOG_LEVEL}
    depends_on:
      db:
        condition: service_healthy
      es:
        condition: service_healthy
    volumes:
      - movies-etl-state:/data

  cache:
    image: redis:5.0.4
    container_name: movies_cache
    restart: always
    env_file:
      - .env
    healthcheck:
      test: [
        "CMD-SHELL",
        "redis-cli ping | grep PONG"
      ]
      interval: 1s
      timeout: 3s
      retries: 5
    command: [ "redis-server" ]

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: movies_api
    restart: always
    env_file:
      - .env
    depends_on:
      es:
        condition: service_healthy
      cache:
        condition: service_healthy

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth_api
    restart: always
    env_file:
      - ./auth/.env
    ports:
      - "8080:8000" # TODO
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

  gateway:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: movies_gateway
    restart: always
    volumes:
      - static-volume:/static
    ports:
      - "80:80"
    depends_on:
      - api
      - auth
      - admin
      - ugc_api
      - ugc_content_api

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: admin
    restart: always
    env_file:
      - ./admin/.env
    volumes:
      - static-volume:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4317:4317"

  kafka:
    image: apache/kafka:4.1.2
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9094,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    volumes:
      - kafka-data:/tmp/kafka-logs

  kafka_init:
    image: apache/kafka:4.1.2
    depends_on:
      - kafka
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "
      until /opt/kafka/bin/kafka-topics.sh
      --bootstrap-server kafka:9092
      --list; do
        echo 'Waiting for Kafka...';
        sleep 2;
      done;
      
      /opt/kafka/bin/kafka-topics.sh
      --bootstrap-server kafka:9092
      --create
      --if-not-exists
      --topic events
      --partitions 3
      --replication-factor 1;
      "
  ugc_api:
    build:
      context: ugc_api
      dockerfile: Dockerfile
    container_name: ugc_api
    env_file:
      - ugc_api/.env
    restart: always
    environment:
      PYTHONPATH: /app/src
    depends_on:
      - kafka_init
    ports:
      - "5001:5000"
    command: python -m flask --app wsgi:app run --host=0.0.0.0 --port=5000
    healthcheck:
      test: [ "CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:5000/health')\"" ]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password
      CLICKHOUSE_DB: movies
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse-data:/var/lib/clichouse

  ugc_etl:
    build:
      context: ./ugc_etl
      dockerfile: Dockerfile
    container_name: ugc_etl
    env_file:
      - ./ugc_etl/.env
    environment:
      PYTHONPATH: /app/src
    restart: always
    depends_on:
      - kafka_init
      - clickhouse
    command: python src/main.py

  mongo:
    image: mongo:8.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ugc_content_api:
    build:
      context: ./ugc_content_api
      dockerfile: Dockerfile
    container_name: ugc_content_api
    env_file:
      - ./ugc_content_api/.env
    restart: always
    depends_on:
      mongo:
        condition: service_healthy

  rabbit:
    image: rabbitmq:4.3.2-management
    container_name: rabbit
    restart: always
    env_file:
      - ./notification/.env
    ports:
      - "15672:15672"
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  migration-notification-service:
    build:
      context: ./notification
      dockerfile: Dockerfile
    env_file:
      - ./notification/.env
    command: alembic upgrade head
    depends_on:
      db:
        condition: service_healthy

  notification-api:
    build:
      context: ./notification
      dockerfile: Dockerfile
    container_name: notification-api
    command: uvicorn notification.api.main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./notification/.env
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      migration-notification-service:
        condition: service_completed_successfully
      rabbit:
        condition: service_healthy

  notification-worker:
    build:
      context: ./notification
      dockerfile: Dockerfile
    env_file:
      - ./notification/.env
    command: python -m notification.worker.main
    depends_on:
      migration-notification-service:
        condition: service_completed_successfully
      rabbit:
        condition: service_healthy
      auth:
        condition: service_started


volumes:
  movies-postgres-data:
  movies-es-data:
  movies-etl-state:
  static-volume:
  kafka-data:
  clickhouse-data:
  mongo-data:
  rabbit-data:
