version: "3.9"

services:
  db:
    image: postgres:16
    container_name: auth_postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
      ]
      interval: 10s
      timeout: 5s
      retries: 3

  cache:
    image: redis:5.0.4
    container_name: auth_cache
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    command: [ "redis-server" ]


  api:
    build: .
    container_name: auth_api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

volumes:
  auth-postgres-data: