"""Create notification table

Revision ID: 7cbb69fab700
Revises:
Create Date: 2026-07-05 16:26:56.304305

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7cbb69fab700"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create notification schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS notification")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("template_code", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="notification",
    )
    op.create_index(
        op.f("ix_notification_notifications_created_at"),
        "notifications",
        ["created_at"],
        unique=False,
        schema="notification",
    )
    op.create_index(
        op.f("ix_notification_notifications_sent_at"),
        "notifications",
        ["sent_at"],
        unique=False,
        schema="notification",
    )
    op.create_index(
        op.f("ix_notification_notifications_status"),
        "notifications",
        ["status"],
        unique=False,
        schema="notification",
    )
    op.create_index(
        op.f("ix_notification_notifications_updated_at"),
        "notifications",
        ["updated_at"],
        unique=False,
        schema="notification",
    )
    op.create_index(
        op.f("ix_notification_notifications_user_id"),
        "notifications",
        ["user_id"],
        unique=False,
        schema="notification",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_notification_notifications_user_id"),
        table_name="notifications",
        schema="notification",
    )
    op.drop_index(
        op.f("ix_notification_notifications_updated_at"),
        table_name="notifications",
        schema="notification",
    )
    op.drop_index(
        op.f("ix_notification_notifications_status"),
        table_name="notifications",
        schema="notification",
    )
    op.drop_index(
        op.f("ix_notification_notifications_sent_at"),
        table_name="notifications",
        schema="notification",
    )
    op.drop_index(
        op.f("ix_notification_notifications_created_at"),
        table_name="notifications",
        schema="notification",
    )
    op.drop_table("notifications", schema="notification")
    # ### end Alembic commands ###
