services:
  postgres:
    image: postgres:16
    container_name: notification_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - notification-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  rabbit:
    image: rabbitmq:4.3.2-management
    container_name: rabbitmq
    restart: always
    env_file:
      - .env
    ports:
      - "15672:15672"
    volumes:
      - notification-rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  notification-api:
    build: .
    container_name: notification-api
    restart: always
    env_file:
      - .env
    command: uvicorn notification.api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      migration:
        condition: service_completed_successfully
      rabbit:
        condition: service_healthy

  migration:
    build: .
    command: alembic upgrade head
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy


  worker:
    build: .
    command: python -m notification.worker.main
    env_file:
      - .env
    depends_on:
      migration:
        condition: service_completed_successfully
      rabbit:
        condition: service_healthy

volumes:
  notification-postgres-data:
  notification-rabbitmq-data: