import uuid
from typing import Protocol

from auth.models.models import Role


class IRoleRepo(Protocol):
    async def get_by_user_id(self, user_id: uuid.UUID) -> list[str]: ...

    async def get_id_by_name(self, name: str) -> uuid.UUID | None: ...

    async def create_role(self, role_name: str) -> None: ...

    async def get_roles(self) -> list[str]: ...

    async def get_by_id(self, role_id: uuid.UUID) -> Role | None: ...

    async def update_role(self, role_id: uuid.UUID, role_name: str) -> None: ...

    async def delete(self, role: Role) -> None: ...
