class InvalidOAuthState(Exception): ...


class OAuthTokenExchangeFailed(Exception): ...


class OAuthUserInfoFailed(Exception): ...


class LinkedOAuthUserNotFound(Exception): ...


class OAuthProviderNotSupported(Exception): ...
